const constants = {
    // ADD_EVENT: "ADD_EVENT",
    // RATE_COLOR: "RATE_COLOR",
    // REMOVE_COLOR: "REMOVE_COLOR",
    // MODAL_SET_DATA: "MODAL_SET_DATA",
    MODAL_LIST: "MODAL_LIST",
    MODAL_HIDDEN: "MODAL_HIDDEN",
    PANEL_STATE: "PANEL_STATE",
    PANEL_BUTTON: "PANEL_BUTTON",
    TEMP_TASK: "TEMP_TASK",
    SET_TASK: "SET_TASK"
}

export default constants