const constants = {
    ADD_EVENT: "ADD_EVENT",
    RATE_COLOR: "RATE_COLOR",
    REMOVE_COLOR: "REMOVE_COLOR",
    MODAL_OPEN: "MODAL_OPEN",
    MODAL_STATE: "MODAL_STATE",
    MODAL_CHECKED: "MODAL_CHECKED",
    TEMP_TASK: "TEMP_TASK",
    SET_TASK: "SET_TASK",
    MODAL_SET_DATA: "MODAL_SET_DATA",
    EVENT_DISPLAY: "EVENT_DISPLAY",
    MODAL_DISPLAY_ID: "MODAL_DISPLAY_ID"
}

export default constants